[project]
name = "baowulearn"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "requests",
    "gmssl",
    "tinydb",
    "pyside6",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 100

[tool.ruff.format]
line-length = 100

[tool.black]
line-length = 100
